# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: env(POSTGRES_USER)
      POSTGRES_PASSWORD: env(POSTGRES_PASSWORD)
      POSTGRES_DB: env(POSTGRES_DB)
    ports:
      - 5432:5432
